name: demo pipeline

on:
  push:
    branches: [ "main" ]

env:
  DOCKER_IMAGE: "dudhaniayush/placement-portal-repository"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build with Maven
        run: mvn clean install -DskipTests

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker Image
        run: docker build -t $DOCKER_IMAGE:latest .

      - name: Push Docker Image
        run: docker push $DOCKER_IMAGE:latest

  deploy:
    needs: build
    runs-on: [ "self-hosted" ]
    steps:
      - name: Check Docker Installation
        run: |
          if ! [ -x "$(command -v docker)" ]; then
            echo "Error: Docker is not installed." >&2
            exit 1
          fi

      - name: Pull Image from Docker Hub
        run: sudo docker pull $DOCKER_IMAGE:latest

      - name: Delete Existing Container
        run: |
          if [ "$(sudo docker ps -aq -f name=demo)" ]; then
            sudo docker stop demo
            sudo docker rm -f demo
          fi

      - name: Clean Up Unused Docker Images
        run: sudo docker system prune -f

      - name: Run Docker Container
        run: sudo docker run -d -p 8080:8080 --name demo $DOCKER_IMAGE:latest
