name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set Up Java & Maven
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Build JAR
      run: mvn clean package -DskipTests

    - name: Deploy to EC2
      env:
        SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
        EC2_HOST: ${{ secrets.EC2_HOST }}
        EC2_USER: ${{ secrets.EC2_USER }}
      run: |
        echo "$SSH_PRIVATE_KEY" > private_key.pem
        chmod 600 private_key.pem
        
        echo "Transferring JAR to EC2..."
        scp -i private_key.pem target/*.jar $EC2_USER@$EC2_HOST:/home/$EC2_USER/app.jar
        
        echo "Deploying on EC2..."
        ssh -i private_key.pem $EC2_USER@$EC2_HOST << 'EOF'
          echo "Stopping old application..."
          if [ -f /home/$EC2_USER/app.pid ]; then
            kill \$(cat /home/$EC2_USER/app.pid) || true
            rm -f /home/$EC2_USER/app.pid
          else
            fuser -k 8080/tcp || true
          fi
          
          echo "Cleaning up old JAR..."
          rm -f /home/$EC2_USER/old-app.jar
          mv /home/$EC2_USER/app.jar /home/$EC2_USER/old-app.jar

          echo "Starting new application..."
          nohup java -jar /home/$EC2_USER/app.jar > /home/$EC2_USER/app.log 2>&1 &
          echo $! > /home/$EC2_USER/app.pid
          
          echo "Deployment successful!"
        EOF
