# name: Deploy to AWS EC2

# on:
#   pull_request:
#     types:
#       - closed  # Only trigger on PR merge
#     branches:
#       - main

# jobs:
#   deploy:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout Code
#         uses: actions/checkout@v3
      
#       - name: Download Built JAR
#         uses: actions/download-artifact@v4
#         with:
#           name: placement-portal-jar
#           path: .

#       - name: Debug Downloaded Artifacts
#         run: |
#           echo "Listing downloaded files:"
#           ls -lah .
          
#       - name: Transfer JAR to EC2
#         run: |
#           scp -o StrictHostKeyChecking=no placement-portal-0.0.1-SNAPSHOT.jar ec2-user@${{ secrets.EC2_HOST }}:/home/ec2-user/deployment/

#       - name: SSH into EC2 and Deploy
#         run: |
#           ssh -o StrictHostKeyChecking=no ec2-user@${{ secrets.EC2_HOST }} << 'EOF'
#             cd /home/ec2-user/deployment
#             ./deploy.sh
#           EOF

#       - name: Run Health Check (Ensure Deployment is Successful)
#         run: |
#           curl --fail http://${{ secrets.EC2_HOST }}:8080/actuator/health || exit 1
