name: Maven Build & Store JAR

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build with Maven
        run: mvn clean package -DskipTests=false

      - name: List Target Directory (Debugging)
        run: ls -lah target

      - name: Upload JAR as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: placement-portal-jar
          path: target/placement-portal-0.0.1-SNAPSHOT.jar

      - name: List Target Directory (Debugging)
        run: ls -lah target
